// Package icons provides Nerd Font icon lookup for file system entries.
package icons

// Icon unicode codepoints (Nerd Fonts v3).
// Using rune(0x...) so codepoints above U+FFFF compile correctly on all Go versions.
var (
	iconAudio        = rune(0xf001)  //
	iconBinary       = rune(0xeae8)  //
	iconCalendar     = rune(0xeab0)  //
	iconCAD          = rune(0xf0eeb) // 󰻫
	iconClock        = rune(0xf43a)  //
	iconCompressed   = rune(0xf410)  //
	iconConfig       = rune(0xf107b) // 󱁻
	iconCSS3         = rune(0xe749)  //
	iconDatabase     = rune(0xf1c0)  //
	iconDiff         = rune(0xf440)  //
	iconDiskImage    = rune(0xe271)  //
	iconDocker       = rune(0xe650)  //
	iconDocument     = rune(0xf1c2)  //
	iconDownload     = rune(0xf01da) // 󰇚
	iconEmacs        = rune(0xe632)  //
	iconEslint       = rune(0xe655)  //
	iconFile         = rune(0xf15b)  //
	iconFile3D       = rune(0xf01a7) // 󰆧
	iconFileUnknown  = rune(0xf086f) // 󰡯
	iconFolder       = rune(0xe5ff)  //
	iconFolderBuild  = rune(0xf19fc) // 󱧼
	iconFolderConfig = rune(0xe5fc)  //
	iconFolderGit    = rune(0xe5fb)  //
	iconFolderGithub = rune(0xe5fd)  //
	iconFolderHidden = rune(0xf179e) // 󱞞
	iconFolderKey    = rune(0xf08ac) // 󰢬
	iconFolderNpm    = rune(0xe5fa)  //
	iconFolderOcaml  = rune(0xe67a)  //
	iconFolderOpen   = rune(0xf115)  //
	iconFont         = rune(0xf031)  //
	iconGimp         = rune(0xf338)  //
	iconGistSecret   = rune(0xeafa)  //
	iconGit          = rune(0xf02a2) // 󰊢
	iconGodot        = rune(0xe65f)  //
	iconGradle       = rune(0xe660)  //
	iconGraph        = rune(0xf1049) // 󱁉
	iconGraphql      = rune(0xe662)  //
	iconGrunt        = rune(0xe611)  //
	iconGTK          = rune(0xf362)  //
	iconGulp         = rune(0xe610)  //
	iconHTML5        = rune(0xf13b)  //
	iconImage        = rune(0xf1c5)  //
	iconInfo         = rune(0xf129)  //
	iconIntellij     = rune(0xe7b5)  //
	iconJSON         = rune(0xe60b)  //
	iconKey          = rune(0xeb11)  //
	iconKeypass      = rune(0xf23e)  //
	iconKrita        = rune(0xf33d)  //
	iconArduino      = rune(0xf34b)  //
	iconAssembly     = rune(0xe637)  //
	iconC            = rune(0xe61e)  //
	iconCpp          = rune(0xe61d)  //
	iconCsharp       = rune(0xf031b) // 󰌛
	iconD            = rune(0xe7af)  //
	iconElixir       = rune(0xe62d)  //
	iconFennel       = rune(0xe6af)  //
	iconFortran      = rune(0xf121a) // 󱈚
	iconFsharp       = rune(0xe7a7)  //
	iconGleam        = rune(0xf09a5) // 󰦥
	iconGo           = rune(0xf07d3) //
	iconGroovy       = rune(0xe775)  //
	iconHaskell      = rune(0xe777)  //
	iconJava         = rune(0xe256)  //
	iconJavaScript   = rune(0xe74e)  //
	iconKotlin       = rune(0xe634)  //
	iconLua          = rune(0xe620)  //
	iconNim          = rune(0xe677)  //
	iconOcaml        = rune(0xe67a)  //
	iconPerl         = rune(0xe67e)  //
	iconPHP          = rune(0xe73d)  //
	iconPython       = rune(0xe606)  //
	iconR            = rune(0xe68a)  //
	iconRuby         = rune(0xe739)  //
	iconRubyRails    = rune(0xe73b)  //
	iconRust         = rune(0xe68b)  //
	iconSass         = rune(0xe603)  //
	iconScheme       = rune(0xe6b1)  //
	iconStylus       = rune(0xe600)  //
	iconTeX          = rune(0xe69b)  //
	iconTypeScript   = rune(0xe628)  //
	iconV            = rune(0xe6ac)  //
	iconLibrary      = rune(0xeb9c)  //
	iconLicense      = rune(0xf02d)  //
	iconLock         = rune(0xf023)  //
	iconLog          = rune(0xf18d)  //
	iconMake         = rune(0xe673)  //
	iconMarkdown     = rune(0xf48a)  //
	iconMustache     = rune(0xe60f)  //
	iconNews         = rune(0xf1ea)  //
	iconNodejs       = rune(0xe718)  //
	iconNotebook     = rune(0xe678)  //
	iconNPM          = rune(0xe71e)  //
	iconAndroid      = rune(0xe70e)  //
	iconApple        = rune(0xf179)  //
	iconLinux        = rune(0xf17c)  //
	iconWindows      = rune(0xf17a)  //
	iconWindowsCmd   = rune(0xebc4)  //
	iconPlaylist     = rune(0xf0cb9) // 󰲹
	iconPowershell   = rune(0xebc7)  //
	iconPrivateKey   = rune(0xf0306) // 󰌆
	iconPublicKey    = rune(0xf0dd6) // 󰷖
	iconRazor        = rune(0xf1fa)  //
	iconReact        = rune(0xe7ba)  //
	iconReadme       = rune(0xf00ba) // 󰂺
	iconSheet        = rune(0xf1c3)  //
	iconShell        = rune(0xf1183) // 󱆃
	iconShellCmd     = rune(0xf489)  //
	iconShieldCheck  = rune(0xf0565) // 󰕥
	iconShieldKey    = rune(0xf0bc4) // 󰯄
	iconShieldLock   = rune(0xf099d) // 󰦝
	iconSlide        = rune(0xf1c4)  //
	iconSqlite       = rune(0xe7c4)  //
	iconSublime      = rune(0xe7aa)  //
	iconSubtitle     = rune(0xf0a16) // 󰨖
	iconTcl          = rune(0xf06d3) // 󰛓
	iconTerraform    = rune(0xf1062) // 󱁢
	iconText         = rune(0xf15c)  //
	iconTodo         = rune(0xf0ae)  //
	iconTypst        = rune(0xf37f)  //
	iconTmux         = rune(0xebc8)  //
	iconToml         = rune(0xe6b2)  //
	iconTranslation  = rune(0xf05ca) // 󰗊
	iconUnity        = rune(0xe721)  //
	iconVector       = rune(0xf0559) // 󰕙
	iconVideo        = rune(0xf03d)  //
	iconVim          = rune(0xe7c5)  //
	iconWrench       = rune(0xf0ad)  //
	iconXML          = rune(0xf05c0) // 󰗀
	iconXorg         = rune(0xf369)  //
	iconYAML         = rune(0xe8eb)  //
	iconYarn         = rune(0xe6a7)  //
	iconSwift        = rune(0xe755)  //
	iconZig          = rune(0xe6a9)  //
	iconVue          = rune(0xf0844) // 󰡄
	iconSvelte       = rune(0xf1b6)  //
	iconNuxt         = rune(0xf1106) // 󱄆
	iconAngular      = rune(0xe753)  //
	iconNextjs       = rune(0xf0ede) // 󰻞
	iconFlutter      = rune(0xe2a1)  //
	iconDart         = rune(0xe798)  //
	iconScala        = rune(0xe737)  //
	iconClojure      = rune(0xe768)  //
	iconElm          = rune(0xe62c)  //
	iconCrystal      = rune(0xe7a3)  //
	iconNix          = rune(0xf313)  //
	iconEnv          = rune(0xf462)  //
	iconEditorconfig = rune(0xe652)  //
	iconBrew         = rune(0xf1116) // 󱄖
	iconJenkins      = rune(0xe66e)  //
	iconAnsible      = rune(0xe647)  //
	iconHelm         = rune(0xe77b)  //
	iconSignedFile   = rune(0xf19c3) // 󱧃
	iconProto        = rune(0xf1049) // reuse graph
	iconWasm         = rune(0xe6a9)  // reuse zig
)
