package icons

// directoryIcons maps exact directory names to icons.
var directoryIcons = map[string]rune{
	".config":      iconFolderConfig,
	".git":         iconFolderGit,
	".github":      iconFolderGithub,
	".npm":         iconFolderNpm,
	".opam":        iconFolderOcaml,
	".ssh":         iconFolderKey,
	".Trash":       rune(0xf1f8),
	"build":        iconFolderBuild,
	"config":       iconFolderConfig,
	"Contacts":     rune(0xf024c),
	"cron.d":       iconFolderConfig,
	"cron.daily":   iconFolderConfig,
	"cron.hourly":  iconFolderConfig,
	"cron.monthly": iconFolderConfig,
	"cron.weekly":  iconFolderConfig,
	"Desktop":      rune(0xf0108),
	"Documents":    rune(0xf0c82),
	"Downloads":    rune(0xf024d),
	"etc":          iconFolderConfig,
	"Favorites":    rune(0xf069d),
	"hidden":       iconFolderHidden,
	"home":         rune(0xf10b5),
	"include":      iconFolderConfig,
	"Mail":         rune(0xf01f0),
	"Movies":       rune(0xf0fce),
	"Music":        rune(0xf1359),
	"node_modules": iconFolderNpm,
	"npm_cache":    iconFolderNpm,
	"pacman.d":     iconFolderConfig,
	"pam.d":        iconFolderKey,
	"Pictures":     rune(0xf024f),
	"src":          rune(0xf08de),
	"ssh":          iconFolderKey,
	"sudoers.d":    iconFolderKey,
	"Videos":       iconVideo,
	"xbps.d":       iconFolderConfig,
	"xorg.conf.d":  iconFolderConfig,
	"cabal":        iconHaskell,
	"terraform":    iconTerraform,
	"ansible":      iconAnsible,
	"helm":         iconHelm,
}
